# Generated by Django 2.2.1 on 2019-06-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='companytable',
        ),
    ]
