# Generated by Django 2.2.1 on 2019-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('company_logp', models.FileField(blank='True', null='True', upload_to='')),
                ('company_city', models.CharField(max_length=40)),
            ],
        ),
    ]
