# Generated by Django 2.2 on 2019-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Dept', models.CharField(max_length=30)),
                ('Date', models.DateField()),
            ],
        ),
    ]
